id: I5B115F3D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:04:11+00:00'
last_modified: '2022-06-08T01:12:53.261398+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14130
  title: གསང་ཆེན་ཐབས་ལམ་ཉེར་མཁོ་རྣལ་འབྱོར་སྙིང་ནོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6329':
      image_group_id: I1PD5292
      title: ''
      total_pages: 186
      order: 1
      base_file: 6329.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
